name: 'data_connector_dbt'

version: '1.0'

config-version: 2

profile: 'data_connector'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_connector_dbt:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table