FROM python:3.11-slim

WORKDIR /usr/app/dbt

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip install \
    dbt-core \
    dbt-postgres

COPY dbt/ .

CMD ["sleep", "infinity"]